name: CI/CD Pipeline for Blogify

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          python -m pytest

  deploy:
    name: Deploy to PythonAnywhere
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pythonanywhere-client
        run: pip install pythonanywhere

      - name: Upload to PythonAnywhere
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          pa_authtoken=$(python -c "import os; print(os.environ['PA_API_TOKEN'])")
          pa deploy \
            --username $PA_USERNAME \
            --api-token $pa_authtoken \
            --path . \
            --domain "$PA_USERNAME.pythonanywhere.com"

      - name: Reload web app
        run: |
          echo "Reloading web app to apply changes..."
          python -m pythonanywhere.reloader \
            --username $PA_USERNAME \
            --api_token $pa_authtoken \
            --site_domain "$PA_USERNAME.pythonanywhere.com"
