name: Blogify CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy (main or develop)'
        required: true
        default: 'main'

jobs:
  lint:
    name: Run Flake8 Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: flake8 app.py tests/

  test:
    name: Run Tests with Coverage and Report
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=app --cov-report=term-missing

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Set Branch Variable
        id: vars
        run: echo "branch=${{ github.event.inputs.branch || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Validate Deployment Hooks
        run: |
          BRANCH="${{ steps.vars.outputs.branch }}"
          if [[ "$BRANCH" == "main" && -z "${{ secrets.RENDER_DEPLOY_HOOK_PROD }}" ]]; then
            echo "Missing production deploy hook"; exit 1
          elif [[ "$BRANCH" == "develop" && -z "${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}" ]]; then
            echo "Missing staging deploy hook"; exit 1
          fi

      - name: Deploying...
        run: |
          BRANCH="${{ steps.vars.outputs.branch }}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "Deploying to PRODUCTION"
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_PROD }}"
          elif [[ "$BRANCH" == "develop" ]]; then
            echo "Deploying to STAGING"
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}"
          else
            echo "Branch $BRANCH is not configured for deployment"; exit 1
          fi

          echo "Waiting for service to warm up..."
          sleep 40

  healthcheck:
    name: Post-Deploy Health Check
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Set Branch Variable
        id: vars
        run: echo "branch=${{ github.event.inputs.branch || github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Check Service Health
        run: |
          BRANCH="${{ steps.vars.outputs.branch }}"
          if [[ "$BRANCH" == "main" ]]; then
            URL="https://blogify-prod.onrender.com/health"
          elif [[ "$BRANCH" == "develop" ]]; then
            URL="https://blogify-staging.onrender.com/health"
          else
            echo "No healthcheck URL configured for branch: $BRANCH"; exit 1
          fi

          echo "Waiting for service to warm up..."
          sleep 40

          echo "Checking service at $URL..."
          status_code=$(curl --write-out '%{http_code}' --silent --output /dev/null "$URL")

          if [[ "$status_code" == "200" ]]; then
            echo "Service is healthy ✅"
          else
            echo "Service healthcheck failed with status $status_code ❌"
            exit 1
          fi
