name: CI/CD Pipeline for Blogify

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest

  deploy:
    name: Deploy to PythonAnywhere
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: SSH into PythonAnywhere and deploy
        env:
          PA_USERNAME: ${{ secrets.PA_USERNAME }}
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          PA_PASSWORD: ${{ secrets.PA_PASSWORD }} # Eğer SSH kullanıyorsan parola değil SSH key önerilir.
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.PA_USERNAME }}@ssh.pythonanywhere.com "
            cd /home/${{ secrets.PA_USERNAME }}/blogify &&
            git pull origin main &&
            workon blogify &&
            touch /var/www/${{ secrets.PA_USERNAME }}_pythonanywhere_com_wsgi.py
          "

